name: 'Apply Integrations Infrastructure'
run-name: Applying infrastructure for ${{ inputs.environment }}

on:
  # push:
  #   paths:
  #     - 'terraform/*.tf'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: Bootstrap environment
        type: environment
        required: true

permissions:
  id-token: write
  contents: read

env:
  TF_PATH: ./terraform
  TF_BACKEND_CONFIG: '${{ github.event.inputs.environment }}.tfbackend'
  TF_VAR_FILE: '${{ github.event.inputs.environment }}.tfvars'

jobs:
  terraform-validate:
    name: 'Terraform Validate'
    runs-on: 'ubuntu-latest'

    defaults:
      run:
        working-directory: ${{ env.TF_PATH }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run:  terraform init -backend=false

      - name: Terraform Format
        run: terraform fmt -check --recursive

      - name: Terraform Validate
        run: terraform validate


  terraform-plan:
    name: 'Terraform-Plan'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_env: ${{ github.event.inputs.environment }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_PATH }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run:  terraform init -backend-config=${{ env.TF_BACKEND_CONFIG }}

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run:  terraform plan -input=false -out=terraform.plan -var-file=${{ env.TF_VAR_FILE }}

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: | 
          ${{ env.TF_PATH }}/terraform.plan
          ${{ env.TF_PATH }}/.terraform.lock.hcl
        if-no-files-found: error 

  approve:
    needs: [terraform-plan,terraform-validate]
    environment: manual-gate
    runs-on: ubuntu-latest
    steps:
    - name: Approval
      run: echo Approved

  terraform-apply:
    name: 'Terraform-Apply'
    needs: [approve]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_env: ${{ github.event.inputs.environment }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ${{ env.TF_PATH }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v4

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get prepared plan
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan
        path: ${{ env.TF_PATH }}
    
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run:  terraform init -backend-config=${{ env.TF_BACKEND_CONFIG }}

    # Generates an execution plan for Terraform
    - name: Terraform Apply
      run:  terraform apply -auto-approve terraform.plan